title: "OUMAR DJIME RATOU"
logo: img/oudjira.jpeg
description: "Ingénieur Cybersécurité | Expert IA & Blockchain"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr



# Configuration markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

